[package]
name = "networking"
version = "0.1.0"
edition = "2024"

[dependencies]
containers = {workspace = true}
alloy-primitives = { workspace = true}
libp2p = {workspace = true}
snap = {workspace = true}
sha2 = { workspace = true }
