[package]
name = "runtime"
edition = { workspace = true }

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true }
enum-iterator = { workspace = true }
fork_choice = { workspace = true }
strum = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
